title: Mohanakannan - Security Blog
description:  AI Security | Cloud Native Security | Security Automation | CISSP :)
theme: jekyll-theme-hacker
markdown: kramdown
url: "https://mohanakannan92.github.io"
baseurl: ""
